name: Trivy Scan

on:
  workflow_call:
    inputs:
      service:
        required: true
        type: string
      version:
        required: true
        type: string
    secrets:
      DOCKERHUB_USERNAME:
        required: true

jobs:
  scan:
    name: Trivy Vulnerability Scan
    runs-on: ubuntu-24.04

    env:
      IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/${{ inputs.service }}:${{ inputs.version }}

    steps:
      - name: Download Image Artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.service }}-image

      - name: Load Image
        run: docker load -i image.tar

      - name: Scan Image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.IMAGE_NAME }}
          format: json
          output: trivy-report.json
          exit-code: '0'
          ignore-unfixed: true
          vuln-type: os,library
          severity: LOW,MEDIUM,HIGH,CRITICAL
          scanners: vuln

      - name: Debug Trivy Report
        run: |
          echo "=== FILE SIZE ==="
          ls -lh trivy-report.json || true

          echo "=== RESULTS LENGTH ==="
          cat trivy-report.json | jq '.Results | length'

          echo "=== VULN COUNT ==="
          cat trivy-report.json | jq '[.Results[]?.Vulnerabilities[]?] | length'

      - name: Print Trivy Table Summary
        run: |
          VULN_COUNT=$(jq '[.Results[]?.Vulnerabilities[]?] | length' trivy-report.json)

          if [ "$VULN_COUNT" -eq 0 ]; then
            echo "No vulnerabilities found"
          else
            echo "Vulnerabilities found: $VULN_COUNT"
            trivy convert --format table trivy-report.json
          fi

      - name: Upload Trivy Report
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.service }}-trivy-report
          path: trivy-report.json
          retention-days: 1

      - name: Fail if CRITICAL vulnerabilities exist
        run: |
          if jq -e '
            .Results[]?.Vulnerabilities[]?
            | select(.Severity=="CRITICAL")
          ' trivy-report.json > /dev/null; then
            echo "HIGH or CRITICAL vulnerabilities found"
            exit 1
          else
            echo "No HIGH or CRITICAL vulnerabilities found"
          fi